monolog:
    handlers:
        client:
            level:    info
            type:     rotating_file
            path:     '%kernel.logs_dir%/%kernel.environment%-client.log'
            channels: [client]
            max_files: 365
        main:
            type: rotating_file
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: ["!event"]
            max_files: 365
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type: firephp
        #    level: info
        #chromephp:
        #    type: chromephp
        #    level: info
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]
        search_log:
            type: rotating_file
            path: '%kernel.logs_dir%/search-terms.log'
            channels: [ "search" ]
            max_files: 365
